update

diff --git a/chart/templates/infra/database/sql-user-set-password.yaml b/chart/templates/infra/database/sql-user-set-password.yaml
--- a/chart/templates/infra/database/sql-user-set-password.yaml
+++ b/chart/templates/infra/database/sql-user-set-password.yaml
@@ -32,32 +32,14 @@ spec:
     name: {{ include "service.fullname" . }}-postgres-password
   role: roles/secretmanager.admin
 ---
-apiVersion: iam.cnrm.cloud.google.com/v1beta1
-kind: IAMPolicyMember
-metadata:
-  name: {{ include "service.fullname" . }}-csql-password-manager
-  labels:
-    {{- include "service.labels" . | nindent 4 }}
-  annotations:
-    argocd.argoproj.io/sync-wave: "-10"
-    cnrm.cloud.google.com/project-id: {{ .Values.gcp.projectId }}
-spec:
-  memberFrom:
-    serviceAccountRef:
-      name: {{ include "service.fullname" . }}-sa
-  resourceRef:
-    kind: Project
-    external: {{ .Values.gcp.projectId }}
-  role: projects/{{ .Values.gcp.projectId }}/roles/cloudSqlUserPasswordManager
----
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: {{ include "service.fullname" . }}-set-gsm-secret
+  name: {{ include "service.fullname" . }}-init-gsm-secret
   labels:
     {{- include "service.labels" . | nindent 4 }}
   annotations:
-    argocd.argoproj.io/sync-wave: "-8"
+    argocd.argoproj.io/sync-wave: "-9"
 spec:
   backoffLimit: 0
   template:
@@ -72,44 +54,24 @@ spec:
             - -c
           args:
             - |
-              echo "Updating Secret..."
-              MAX_RETRIES=12
-              RETRY_DELAY=10
-              COUNT=0
-
-              while [ $COUNT -lt $MAX_RETRIES ]; do
-                SECRET_VALUE=$(openssl rand -base64 32 | tr -d '\n')
-
-                if echo -n "$SECRET_VALUE" | gcloud secrets versions add {{ include "service.fullname" . }}-postgres-password --data-file=- --project {{ .Values.gcp.projectId }} &&
-                  #  kubectl delete externalsecret {{ include "service.fullname" . }}-secret-env -n {{ .Release.Namespace }} --ignore-not-found &&
-                   gcloud sql users set-password {{ include "service.fullname" . }} --instance={{ .Values.gcp.database.instanceName }} --password=$SECRET_VALUE; then
-                  echo "Updated Secret successfully."
-                  exit 0
-                else
-                  echo "Failed to update secret. Retrying in $RETRY_DELAY seconds... ($((COUNT+1))/$MAX_RETRIES)"
-                  COUNT=$((COUNT+1))
-                  sleep $RETRY_DELAY
-                fi
-              done
-
-              echo "Failed to update secret after $MAX_RETRIES attempts. Exiting."
-              exit 1
+              echo "Creating initial password in Secret Manager..."
+              SECRET_VALUE=$(openssl rand -base64 32 | tr -d '\n')
+              
+              if echo -n "$SECRET_VALUE" | gcloud secrets versions add {{ include "service.fullname" . }}-postgres-password --data-file=- --project {{ .Values.gcp.projectId }}; then
+                echo "Initial password created successfully."
+                exit 0
+              else
+                echo "Failed to create initial password."
+                exit 1
+              fi
           env:
             - name: PROJECT_ID
               value: {{ .Values.gcp.projectId }}
-            - name: APP_NAME
-              value: {{ include "service.fullname" . }}
-            - name: INSTANCE_NAME
-              value: {{ .Values.gcp.database.instanceName }}
-            - name: NAMESPACE
-              valueFrom:
-                fieldRef:
-                  fieldPath: metadata.namespace
           resources:
             limits:
-              cpu: 1000m
-              memory: 200Mi
+              cpu: 500m
+              memory: 128Mi
             requests:
-              cpu: 25m
-              memory: 200Mi
+              cpu: 100m
+              memory: 64Mi
 {{- end }}
